# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=myapp
    ports:
      - '3307:3306'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=myapp
      - DB_DATABASE=myappdb
      - DB_DATABASE_TEST=testdb
    volumes:
      - './:/app'
    depends_on:
      - mariadb