version: '2'

services:

  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=myapp
    ports:
      - '3307:3306'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - expenses-api


  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
    networks:
      - expenses-api

  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=myapp
      - DB_DATABASE=myappdb
      - DB_DATABASE_TEST=testdb
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME="${APP_NAME}"
    volumes:
      - './:/app'
    networks:
      - expenses-api
    depends_on:
      - mariadb
      - mailhog
networks:
  expenses-api:
    name: expenses-api
    driver: bridge
